imagemap = {
    "": "blank",
    "Acheron": "acheron",
    "Argenti": "argenti",
    "Aventurine": "aventurine",
    "Bailu": "bailu",
    "Black Swan": "blackswan",
    "Blade": "blade",
    "Boothill": "boothill",
    "Bronya": "bronya",
    "Clara": "clara",
    "Dan Heng IL": "dhil",
    "Dr Ratio": "drratio",
    "Firefly": "firefly",
    "Fu Xuan": "fuxuan",
    "Gepard": "gepard",
    "Himeko": "himeko",
    "Huohuo": "huohuo",
    "Jade": "jade",
    "Jing Yuan": "jingyuan",
    "Jingliu": "jingliu",
    "Kafka": "kafka",
    "Luocha": "luocha",
    "Robin": "robin",
    "Ruan Mei": "ruanmei",
    "Seele": "seele",
    "Silver Wolf": "silverwolf",
    "Sparkle": "hanabi",
    "Topaz": "topaz",
    "Welt": "welt",
    "Yanqing": "yanqing",
    "March 7th": "mitsuki",
    "Dan Heng": "danheng",
    "Arlan": "arlan",
    "Asta": "asta",
    "Herta": "herta",
    "Serval": "serval",
    "Natasha": "natasha",
    "Pela": "pela",
    "Sampo": "sampo",
    "Hook": "hook",
    "Lynx": "lynx",
    "Luka": "luka",
    "Qingque": "qingque",
    "Tingyun": "tingyun",
    "Sushang": "sushan",
    "Yukong": "yukong",
    "Guinaifen": "guinaifen",
    "Xueyi": "xueyi",
    "Hanya": "hanya",
    "Gallagher": "gallagher",
    "Misha": "misha",
    "Night on the Milky Way": "notmw",
    "In the Night": "itn",
    "Something Irreplaceable": "si",
    "But the Battle Isn't Over": "btbio",
    "In the Name of the World": "itnotw",
    "Moment of Victory": "mov",
    "Patience is All You Need": "piayn",
    "Incessant Rain": "ir",
    "Echoes of the Coffin": "eotc",
    "The Unreachable Side": "tus",
    "Before Dawn": "bd",
    "She Already Shut Her Eyes": "sashe",
    "Sleep Like the Dead": "sltd",
    "Time Waits for No One": "twfno",
    "I Shall Be My Own Sword": "isbmos",
    "Brighter Than the Sun": "btts",
    "Worrisome: Blissful": "wb",
    "On the Fall of an Aeon": "otfoaa",
    "Cruising in the Stellar Sea": "citss",
    "Texture of Memories": "tom",
    "Night of Fright": "nof",
    "An Instant Before A Gaze": "aibag",
    "Past Self In Mirror": "psim",
    "Earthly Escapade": "ee",
    "Inherent Unjust Destiny": "iud",
    "Baptism of Pure Thought": "bopt",
    "Solitary Healing": "sh",
    "Reforged Remembrance": "rr",
    "Eternal Calculus": "ec",
    "Along the Passing Shore": "atps",
    "Where Should Dreams Rest": "wsdr",
    "Yet Hope Is Priceless": "yhip",
    "Sailing Towards a Second Life": "stasl",
    "Flowing Nightglow": "fn",
    "Extinguished Core": "invec",
    "Thief's Instinct": "invti",
    "Silvermane Badge": "invsba",
    "Ancient Part": "invap",
    "Immortal Scionette": "invis",
    "Artifex's Module": "invam",
    "Dream Collection Component": "invdcc",
    "Tatters of Thought": "invtot",
    "Glimmering Core": "invgc",
    "Usurper's Scheme": "invus",
    "Silvermane Insignia": "invsi",
    "Ancient Spindle": "invas",
    "Immortal Aeroblossom": "invia",
    "Artifex's Cogwheel": "invac",
    "Dream Flow Valve": "invdfv",
    "Fragments of Impression": "invfoi",
    "Squirming Core": "invsc",
    "Conqueror's Will": "invcw",
    "Silvermane Medal": "invsm",
    "Ancient Engine": "invae",
    "Immortal Lumintwig": "invil",
    "Artifex's Gyreheart": "invag",
    "Dream Making Engine": "invdme",
    "Shards of Desires": "invsod",
    "Teeth of Iron Wolf": "bossbtoiw",
    "Void Cast Iron": "bossvci",
    "Endotherm Chitin": "bossec",
    "Horn of Snow": "bosshos",
    "Lightning Crown": "bosselcotps",
    "Storm Eye": "bossse",
    "Golden Crown": "bossgcotps",
    "Netherworld Token": "bossnt",
    "Searing Steel": "bossssb",
    "Gelid Chitin": "bossgc",
    "Lightning Staff": "bossssls",
    "Ascendant Debris": "bossad",
    "Nail of the Ape": "bossnota",
    "Suppressing Edict": "bosssed",
    "IPC Work Permit": "bossipc",
    "Raging Heart": "bossrh",
    "Dream Fridge": "bossdfr",
    "Dream Flamer": "bossdfl",
    "Shattered Blade": "invsb",
    "Arrow of the Beast Hunter": "invaotbh",
    "Key of Inspiration": "invkoi",
    "Endurance of Bronze": "inveob",
    "Obsidian of Dread": "invoodr",
    "Harmonic Tune": "invht",
    "Seed of Abundance": "invsoab",
    "Borisin Teeth": "invbt",
    "Meteoric Bullet": "invmb",
    "Rough Sketch": "invrs",
    "Scattered Stardust": "invss",
    "Fiery Spirit": "invfs",
    "Firmament Note": "invfn",
    "Lifeless Blade": "invlb",
    "Arrow of the Demon Slayer": "invaotds",
    "Key of Knowledge": "invkok",
    "Oath of Steel": "invoos",
    "Obsidian of Desolation": "invoode",
    "Ancestral Hymn": "invah",
    "Sprout of Life": "invsol",
    "Lupitoxin Sawteeth": "invls",
    "Destined Expiration": "invde",
    "Dynamic Outlining": "invdo",
    "Crystal Meteorites": "invcm",
    "Starfire Essence": "invse",
    "Celestial Section": "invcs",
    "Worldbreaker Blade": "invwb",
    "Arrow of the Starchaser": "invaots",
    "Key of Wisdom": "invkow",
    "Safeguard of Amber": "invsoam",
    "Obsidian of Obsession": "invooo",
    "Stellaris Symphony": "invssym",
    "Flower of Eternity": "invfoe",
    "Moon Madness Fang": "invmmf",
    "Countertemporal Shot": "invcsh",
    "Exquisite Coloured Draft": "invecd",
    "Divine Amber": "invda",
    "Heaven Incinerator": "invhi",
    "Heavenly Melody": "invhm",
    "Alien Tree Seed": "invats",
    "Nourishing Honey": "invnh",
    "Myriad Fruit": "invmf",
    "Destroyer Road": "wbossdfr",
    "Guardian Lament": "wbossgl",
    "Regret Ochema": "wbossroio",
    "Past Evils": "wbosspeotbpd",
    "Lost Echo": "wbossleotsw",
    "Tracks of Destiny": "invtrode",
    "Wandering Cloud": "relwancl",
    "Wild Wheat": "relwilwh",
    "Purity Palace": "relpupal",
    "Glacial Forest": "relglahu",
    "Streetwise Boxing": "relstrbo",
    "Wuthering Snow": "relwusno",
    "Lava-Forging": "rellava",
    "Brilliant Stars": "relbrist",
    "Sizzling Thunder": "relsizth",
    "Twilight Line": "reltwili",
    "Shooting Meteor": "relshome",
    "Banditry Desert": "relbandi",
    "Longevous Disciple": "rellonge",
    "Hackerspace": "relhacke",
    "Grand Duke": "relgrduk",
    "Deep Confinement": "reldecon",
    "Dead Waters": "reldewat",
    "Dream Machinations": "relwatch",
    "Iron Cavalry": "relircav",
    "Valourous": "relvalor",
    "Space Sealing": "relspsea",
    "Fleet of Ageless": "relfleet",
    "Cosmic Enterprise": "relcomen",
    "Belobog of Architects": "relbebog",
    "Differentiator": "relceldi",
    "Inert Salsotto": "relinert",
    "Kingdom of Banditry": "reltalia",
    "Sprightly Vonwacq": "relspval",
    "Rutilant Arena": "relarena",
    "Broken Keel": "relbrkel",
    "Firmament Frontline": "relglamo",
    "Penacony": "relpenac",
    "Sigonia": "relsigon",
    "Izumo Gensei": "relizumo",
    "Duran Dynasty": "relduran",
    "Kalpagni Lantern": "relkalpa",
}

commonmats = {
    "": ["", "", ""],
    "Core": ["Extinguished Core", "Glimmering Core", "Squirming Core"],
    "Thief": ["Thief's Instinct", "Usurper's Scheme", "Conqueror's Will"],
    "Silvermane": ["Silvermane Badge", "Silvermane Insignia", "Silvermane Medal"],
    "Ancient": ["Ancient Part", "Ancient Spindle", "Ancient Engine"],
    "Immortal": ["Immortal Scionette", "Immortal Aeroblossom", "Immortal Lumintwig"],
    "Artifex": ["Artifex's Module", "Artifex's Cogwheel", "Artifex's Gyreheart"],
    "Dream": ["Dream Collection Component", "Dream Flow Valve", "Dream Making Engine"],
    "Thought": ["Tatters of Thought", "Fragments of Impression", "Shards of Desires"],
}

tracemats = {
    "": ["", "", ""],
    "Blade": ["Shattered Blade", "Lifeless Blade", "Worldbreaker Blade"],
    "Arrow": [
        "Arrow of the Beast Hunter",
        "Arrow of the Demon Slayer",
        "Arrow of the Starchaser",
    ],
    "Key": ["Key of Inspiration", "Key of Knowledge", "Key of Wisdom"],
    "Endurance": ["Endurance of Bronze", "Oath of Steel", "Safeguard of Amber"],
    "Obsidian": [
        "Obsidian of Dread",
        "Obsidian of Desolation",
        "Obsidian of Obsession",
    ],
    "Tune": ["Harmonic Tune", "Ancestral Hymn", "Stellaris Symphony"],
    "Seed": ["Seed of Abundance", "Sprout of Life", "Flower of Eternity"],
    "Teeth": ["Borisin Teeth", "Lupitoxin Sawteeth", "Moon Madness Fang"],
    "Bullet": ["Meteoric Bullet", "Destined Expiration", "Countertemporal Shot"],
    "Sketch": ["Rough Sketch", "Dynamic Outlining", "Exquisite Coloured Draft"],
    "Stardust": ["Scattered Stardust", "Crystal Meteorites", "Divine Amber"],
    "Fire": ["Fiery Spirit", "Starfire Essence", "Heaven Incinerator"],
    "Note": ["Firmament Note", "Celestial Section", "Heavenly Melody"],
    "Alien": ["Alien Tree Seed", "Nourishing Honey", "Myriad Fruit"],
}
